#powerlevel10k prompt
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
source /opt/homebrew/share/powerlevel10k/powerlevel10k.zsh-theme
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

#stuff
export EDITOR='vim'
export ARCHFLAGS="-arch $(uname -m)"
#export TERM=xterm-256color
export LC_CTYPE=en_US.UTF-8

#path for homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"

#my paths
export PATH=~/bin:~/.local/bin:$PATH

#alias - change default commands to something better
source ~/.aliasrc


#functions
source ~/.functionsrc

#check if there is a tmux session, connect if there is otherwise start new one
[ -z "$TMUX"  ] && {  tmux new-session && exit;} ; hyfetch

